# Stage 1: Build Angular app
FROM node:18 AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --configuration frontend

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Удалим дефолтный конфиг nginx и скопируем наш
COPY nginx.conf /etc/nginx/nginx.conf

# Копируем собранный Angular проект
COPY --from=build /app/dist/frontend/ /usr/share/nginx/html

EXPOSE 80
