spring:
  application:
    name: chess-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://chess-db-petros607.db-msk0.amvera.tech:5432/admin
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.web: DEBUG
server:
  cors:
    origins: "http://localhost:4200,https://chessbratchikov.ru"

