const http = 'https://';
const ws = 'wss://';
const serverHost = 'chessbratchikov.ru';
const frontHost = 'chessbratchikov.ru';
const restPrefix = '/chess';
const topicPrefix = '/topic';
const api = '/api'
export const restUrl = http + serverHost + api + restPrefix
export const restRooms = restUrl + '/rooms'
export const restUsers = restUrl + '/users'
export const restRoomsLink = http + frontHost + restPrefix + '/rooms'
export const restGamePlay = restUrl + '/games';
export const restChat = restUrl + '/chats';
export const restHistory = restUrl + '/history';

export const wsConnect = ws + serverHost + '/api' + '/ws'
export const wsRooms = topicPrefix + '/rooms'
export const wsGamePlay = topicPrefix + '/games';
export const wsChat = topicPrefix + '/chats';
